# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 704a6a5acff95abc7c11015f4a5a16b2dd1fc75e34466c4d86137a751af19d15f97f302afaa6f046ad88cff5c43f7d5d319489ec65e1ad48e334df7c7db0649c

test:
  secret_key_base: d88fe0382033739e2e9b5c14ddbaee63e5a5ba4f1c5b0e70aec5d988606e69a48c6e1701e8d3486c8d4439ff9eb6ee3724f0709bb8685169aca1f740411a2c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
